### ISSUE TITLE
Unity 2017.3 빌드 에러

### ISSUE THREAD

**Issue by parnmanas** [ONE-store/iap_v5#3]
유니티 2017.3 에서 해당 샘플을 빌드 하면 아래와 같은 에러가 납니다.
유니티 5.6 버전까지만 지원하는 것인지 확인 부탁드립니다.

===== Gradle 빌드시
CommandInvokationFailure: Gradle build failed. 
C:/Repository/AndroidSDKs/jdk1.8.0_112\bin\java.exe -classpath "C:\Program Files\Unity2017.3\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-4.0.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx2048m" "assembleRelease"

stderr[

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/onestore/extern/iap/IInAppPurchaseService;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 2m 8s
]
===== Internal 빌드시
CommandInvokationFailure: Unable to convert classes into dex format.
C:/Repository/AndroidSDKs/jdk1.8.0_112\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:/Repository/AndroidSDKs/android-sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity2017.3\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/onestore/extern/iap/IInAppPurchaseService;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/onestore/extern/iap/IInAppPurchaseService$Stub;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/onestore/extern/iap/IInAppPurchaseService$Stub$Proxy;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/onestore/iap/api/AppInstaller;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/onestore/iap/api/AppInstaller$1;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/onestore/iap/api/AppInstaller$2;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/onestore/iap/api/BundleProtocol;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/onestore/iap/api/BundleProtocol$ProductDetailResponse;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/onestore/iap/api/BundleProtocol$PurchaseResult;

**Comment by powerji2001** [comment]
already added 라고 되어 있는것을 보아 aar과 jar 2개가 모두 적용되어 있는 것으로 보입니다.
SDK를 import한 자세한 형상을 보여주시면 대응이 쉬울 거 같습니다.

**Comment by parnmanas** [comment]
2017.3.1f 에서 열어서 빌드해도 같은 에러가 나왔습니다.

확인 부탁드립니다.

감사합니다~

네이버 메일 앱에서 보냈습니다.
-----Original Message-----
보낸사람: "powerji2001" <notifications@github.com>
받는사람: "ONE-store/iap_v5" <iap_v5@noreply.github.com>
참조: "parnmanas" <parn@naver.com>,"Author" <author@noreply.github.com>
날짜: 2018.06.07 오후 02:13:17
제목: Re: [ONE-store/iap_v5] Unity 2017.3 빌드 에러 (#3)

already added 라고 되어 있는것을 보아 aar과 jar 2개가 모두 적용되어 있는 것으로 보입니다.
SDK를 import한 자세한 형상을 보여주시면 대응이 쉬울 거 같습니다.

**Comment by powerji2001** [comment]
Unity_Plugin/IapV17_UnitySampleApp/Assets/Plugins/Android에 보시면  aar과 jar 파일이 같이 존재합니다. aar 제거 후 빌드해보시기 바랍니다.
